#!/usr/bin/env python3
"""Ship a self-hosted display face — B2-04 / D6 repair.

The B2-03 critique (D6) found the site's "three voices" were system font stacks: no `@font-face`,
no shipped font file, and a display stack that degrades to Times New Roman on a stock Windows
machine. G1 — the gap this redesign was commissioned to close — named "system fonts" first.

Why this is hand-rolled: the build is stdlib-only by design (`tools/build_site.py` has no
third-party imports), and no font tooling (fonttools, woff2, fontforge) is available in this
environment; `pip` is not permitted here. A minimal TrueType sub-setter is ~200 lines of stdlib
work and needs no network. It produces a subset of a licence-clear face vendored into this repo
so the build stays offline and byte-reproducible:

    tools/font_sources/Spectral-Regular.ttf   (SIL OFL 1.1)
    tools/font_sources/Spectral-Bold.ttf      (SIL OFL 1.1)

B2-09 / D6: the previous shipped face was a subset of DejaVu Serif — permissive but generic and
mechanical, and the art direction's own target was a Charter/Iowan-class editorial serif. Spectral
(Production Type, OFL 1.1) is a distinctive screen-first editorial serif with real display
character; it is the identity face now. Sources, licence text and hashes are in
`tools/font_sources/`.

The subset keeps only the glyphs the site can actually set in the display voice. The face is
shipped as a WOFF-less TTF, which every current browser renders; its size is what made the
subset necessary (the full face is ~380 KB, the subset is a fraction of that).

Usage:
    python3 tools/make_font.py                # writes docs/assets/fonts/*.ttf
    python3 tools/make_font.py --check        # verify the shipped files against the sources
    python3 tools/font_inspect.py <file.ttf>  # dump the table directory + the cmap structure
"""

from __future__ import annotations

import argparse
import hashlib
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "docs" / "assets" / "fonts"

# Sources: a licence-clear face vendored into the repo (`tools/font_sources/`). Spectral is
# released under the SIL Open Font License 1.1 with no Reserved Font Name declared, which allows
# redistribution of a modified (sub-setted) copy with the copyright notice and licence text kept.
SOURCES = {
    "SpectralSubset-Regular.ttf": ROOT / "tools" / "font_sources" / "Spectral-Regular.ttf",
    "SpectralSubset-Bold.ttf": ROOT / "tools" / "font_sources" / "Spectral-Bold.ttf",
}

KEEP_TABLES = ["head", "hhea", "maxp", "OS/2", "hmtx", "cmap", "loca", "glyf", "name", "post",
               "cvt ", "fpgm", "prep", "gasp"]

# Everything the display voice can be asked to set: ASCII, the Latin-1 letters the site uses
# (résumé), the typographic marks in the copyform (— – ’ “ ” · × …), and the arrow used in the
# work rows. Anything else falls through to the stack that follows the shipped face.
EXTRA_CHARS = "éèêëàâäîïôöûüçñÉÈÀÂÄÎÏÔÖÛÜÇÑ–—’‘“”·×…→≈§†‡•"

FAMILY = "Spectral Subset"
PS_FAMILY = "SpectralSubset"
LICENCE_NOTICE = ("SIL Open Font License 1.1 — Spectral, Copyright 2017 The Spectral Project "
                  "Authors (https://github.com/productiontype/Spectral); subset generated by "
                  "tools/make_font.py — see docs/assets/fonts/LICENCE.txt")
LICENCE_URL = "https://openfontlicense.org"


# --------------------------------------------------------------------------- sfnt reading

class Font:
    def __init__(self, data: bytes) -> None:
        self.data = data
        self.tables: dict[str, bytes] = {}
        num_tables = struct.unpack(">H", data[4:6])[0]
        for i in range(num_tables):
            rec = 12 + i * 16
            tag = data[rec:rec + 4].decode("latin-1")
            offset, length = struct.unpack(">II", data[rec + 8:rec + 16])
            self.tables[tag] = data[offset:offset + length]


def num_glyphs(font: Font) -> int:
    return struct.unpack(">H", font.tables["maxp"][4:6])[0]


def glyph_offsets(font: Font) -> list[int]:
    head = font.tables["head"]
    long_format = struct.unpack(">h", head[50:52])[0] == 1
    loca = font.tables["loca"]
    n = num_glyphs(font) + 1
    fmt = ">%dI" % n if long_format else ">%dH" % n
    values = struct.unpack(fmt, loca[:n * (4 if long_format else 2)])
    return [v if long_format else v * 2 for v in values]


def cmap_unicode_map(font: Font) -> dict[int, int]:
    """(3,1) or (3,10) or (0,x) subtable → {codepoint: glyph id}."""
    data = font.tables["cmap"]
    n = struct.unpack(">H", data[2:4])[0]
    best = None
    for i in range(n):
        rec = 4 + i * 8
        plat, enc = struct.unpack(">HH", data[rec:rec + 4])
        off = struct.unpack(">I", data[rec + 4:rec + 8])[0]
        if (plat, enc) in ((3, 1), (3, 10), (0, 3), (0, 4)):
            best = off if best is None else best
            if (plat, enc) == (3, 10):
                best = off
    if best is None:
        raise SystemExit("no usable cmap subtable")
    fmt = struct.unpack(">H", data[best:best + 2])[0]
    out: dict[int, int] = {}
    if fmt == 4:
        seg_x2 = struct.unpack(">H", data[best + 6:best + 8])[0]
        seg = seg_x2 // 2
        base = best + 14
        ends = struct.unpack(">%dH" % seg, data[base:base + seg_x2])
        starts = struct.unpack(">%dH" % seg, data[base + seg_x2 + 2:base + 2 * seg_x2 + 2])
        deltas = struct.unpack(">%dh" % seg, data[base + 2 * seg_x2 + 2:base + 3 * seg_x2 + 2])
        range_off_base = base + 3 * seg_x2 + 2
        ranges = struct.unpack(">%dH" % seg, data[range_off_base:range_off_base + seg_x2])
        for i in range(seg):
            for cp in range(starts[i], min(ends[i], 0xFFFF) + 1):
                if ranges[i] == 0:
                    gid = (cp + deltas[i]) & 0xFFFF
                else:
                    addr = range_off_base + i * 2 + ranges[i] + (cp - starts[i]) * 2
                    if addr + 2 > len(data):
                        continue
                    gid = struct.unpack(">H", data[addr:addr + 2])[0]
                    if gid:
                        gid = (gid + deltas[i]) & 0xFFFF
                if gid:
                    out[cp] = gid
    elif fmt == 12:
        ngroups = struct.unpack(">I", data[best + 12:best + 16])[0]
        for i in range(ngroups):
            rec = best + 16 + i * 12
            start, end, gid0 = struct.unpack(">III", data[rec:rec + 12])
            for cp in range(start, end + 1):
                out[cp] = gid0 + (cp - start)
    else:
        raise SystemExit(f"unsupported cmap format {fmt}")
    return out


def glyf_composite_components(glyf: bytes, offset: int, length: int) -> list[int]:
    """Component glyph ids of a composite glyph (empty for a simple glyph)."""
    if length == 0:
        return []
    n_contours = struct.unpack(">h", glyf[offset:offset + 2])[0]
    if n_contours >= 0:
        return []
    out: list[int] = []
    p = offset + 10
    end = offset + length
    while p + 4 <= end:
        flags, index = struct.unpack(">HH", glyf[p:p + 4])
        out.append(index)
        p += 4
        if flags & 0x0001:      # ARG_1_AND_2_ARE_WORDS
            p += 4
        else:
            p += 2
        if flags & 0x0008:
            p += 2              # SCALE
        elif flags & 0x0040:
            p += 4              # X_AND_Y_SCALE
        elif flags & 0x0080:
            p += 8              # TWO_BY_TWO
        if not (flags & 0x0020):
            break
    return out


# --------------------------------------------------------------------------- sfnt writing

def checksum(data: bytes) -> int:
    padded = data + b"\0" * ((4 - len(data) % 4) % 4)
    total = 0
    for i in range(0, len(padded), 4):
        total = (total + struct.unpack(">I", padded[i:i + 4])[0]) & 0xFFFFFFFF
    return total


def build_cmap4(pairs: dict[int, int]) -> bytes:
    """A format-4 subtable: one segment per contiguous run of codepoints."""
    cps = sorted(pairs)
    segments: list[tuple[int, int, int, int]] = []
    start = prev = cps[0]
    for cp in cps[1:]:
        if cp == prev + 1 and pairs[cp] == pairs[prev] + 1:
            prev = cp
            continue
        segments.append((start, prev, pairs[start] - start, 0))
        start = prev = cp
    segments.append((start, prev, pairs[start] - start, 0))
    segments.append((0xFFFF, 0xFFFF, 1, 0))     # sentinel: maps U+FFFF to glyph 0

    ends = b"".join(struct.pack(">H", s[1]) for s in segments)
    starts = b"".join(struct.pack(">H", s[0]) for s in segments)
    deltas = b"".join(struct.pack(">h", s[2]) for s in segments)
    ranges = b"".join(struct.pack(">H", s[3]) for s in segments)
    seg_count = len(segments)
    seg_x2 = seg_count * 2
    search_range = 2 * (2 ** (seg_count.bit_length() - 1))
    entry_selector = search_range.bit_length() - 2
    range_shift = seg_x2 - search_range
    length = 16 + 8 * seg_count
    body = (struct.pack(">HHHH", 4, length, 0, seg_x2)
            + struct.pack(">HHH", search_range, entry_selector, range_shift)
            + ends + b"\0\0" + starts + deltas + ranges)
    return body


def build_name() -> bytes:
    records = [
        (0, "Spectral: Copyright 2017 The Spectral Project Authors "
            "(https://github.com/productiontype/Spectral); SIL Open Font License 1.1. Subset "
            "generated by tools/make_font.py."),
        (1, FAMILY),
        (2, "Regular"),
        (3, f"{PS_FAMILY};subset"),
        (4, FAMILY),
        (5, "Version 1.0 (subset)"),
        (6, PS_FAMILY),
        (13, LICENCE_NOTICE),
        (14, LICENCE_URL),
    ]
    count = len(records)
    storage = b""
    entries = b""
    for name_id, value in records:
        payload = value.encode("utf-16-be")
        entries += struct.pack(">HHHHHH", 3, 1, 0x409, name_id, len(payload), len(storage))
        storage += payload
    header = struct.pack(">HHH", 0, count, 6 + count * 12)
    return header + entries + storage


def hmetrics(font: Font, gid: int) -> tuple[int, int]:
    """(advanceWidth, lsb) for a glyph, honouring the hmtx long-metric run boundary.

    hmtx = numberOfHMetrics × (advanceWidth, lsb) followed by (numGlyphs - numberOfHMetrics) ×
    lsb. Reading `gid * 4` past that boundary (which the first version of this script did) yields
    garbage advances for the higher glyph ids and makes the whole face fail to parse.
    """
    hmtx = font.tables["hmtx"]
    n_metrics = struct.unpack(">H", font.tables["hhea"][34:36])[0]
    if gid < n_metrics:
        return struct.unpack(">Hh", hmtx[gid * 4:gid * 4 + 4])
    advance = struct.unpack(">H", hmtx[(n_metrics - 1) * 4:(n_metrics - 1) * 4 + 2])[0]
    pos = n_metrics * 4 + (gid - n_metrics) * 2
    lsb = struct.unpack(">h", hmtx[pos:pos + 2])[0]
    return advance, lsb


def subset(path: Path, wanted: set[int]) -> bytes:
    font = Font(path.read_bytes())
    cmap = cmap_unicode_map(font)
    gids = {0}
    for cp in sorted(wanted):
        if cp in cmap:
            gids.add(cmap[cp])

    # composite closure: a kept composite glyph needs the glyphs it is built from
    offsets = glyph_offsets(font)
    glyf = font.tables["glyf"]
    pending = list(gids)
    while pending:
        gid = pending.pop()
        if gid >= len(offsets) - 1:
            continue
        start, end = offsets[gid], offsets[gid + 1]
        for comp in glyf_composite_components(glyf, start, end - start):
            if comp not in gids:
                gids.add(comp)
                pending.append(comp)

    keep = sorted(gids)
    new_index = {gid: i for i, gid in enumerate(keep)}

    glyf_out = bytearray()
    loca_out = []
    for gid in keep:
        loca_out.append(len(glyf_out))
        if gid + 1 >= len(offsets):
            continue
        chunk = glyf[offsets[gid]:offsets[gid + 1]]
        if not chunk:
            continue
        # a composite's component ids are renumbered to the subset's order
        comps = glyf_composite_components(glyf, offsets[gid], offsets[gid + 1] - offsets[gid])
        if comps:
            chunk = bytearray(chunk)
            p = 10
            for _ in comps:
                flags, index = struct.unpack(">HH", chunk[p:p + 4])
                chunk[p + 2:p + 4] = struct.pack(">H", new_index.get(index, 0))
                p += 4
                p += 4 if flags & 0x0001 else 2
                if flags & 0x0008:
                    p += 2
                elif flags & 0x0040:
                    p += 4
                elif flags & 0x0080:
                    p += 8
                if not (flags & 0x0020):
                    break
            chunk = bytes(chunk)
        glyf_out += chunk
        while len(glyf_out) % 4:
            glyf_out.append(0)
    loca_out.append(len(glyf_out))

    hmtx_out = bytearray()
    for gid in keep:
        hmtx_out += struct.pack(">Hh", *hmetrics(font, gid))

    maxp = bytearray(font.tables["maxp"])
    struct.pack_into(">H", maxp, 4, len(keep))

    head = bytearray(font.tables["head"])
    struct.pack_into(">h", head, 50, 1)              # indexToLocFormat = long
    struct.pack_into(">I", head, 8, 0)               # checkSumAdjustment, recomputed below

    hhea = bytearray(font.tables["hhea"])
    struct.pack_into(">H", hhea, 34, len(keep))      # numberOfHMetrics

    new_cmap = cmap_build({cp: new_index[cmap[cp]] for cp in sorted(wanted)
                           if cp in cmap and cmap[cp] in new_index})

    tables = {
        "head": bytes(head),
        "hhea": bytes(hhea),
        "maxp": bytes(maxp),
        "OS/2": font.tables["OS/2"],
        "hmtx": bytes(hmtx_out),
        "cmap": new_cmap,
        "loca": b"".join(struct.pack(">I", v) for v in loca_out),
        "glyf": bytes(glyf_out),
        "name": build_name(),
        "post": struct.pack(">IIhhIIIII", 0x00030000, 0, 0, 0, 0, 0, 0, 0, 0),
    }
    for tag in ("cvt ", "fpgm", "prep", "gasp"):
        if tag in font.tables:
            tables[tag] = font.tables[tag]

    return assemble(tables)


def cmap_build(pairs: dict[int, int]) -> bytes:
    """cmap header (version 0, one table) + a (3,1) encoding record + the format-4 subtable.

    The encoding record's offset is relative to the start of the cmap table, and the subtable is
    the format-4 table itself — not a second copy of the record.
    """
    sub = build_cmap4(pairs)
    return struct.pack(">HH", 0, 1) + struct.pack(">HHI", 3, 1, 12) + sub


def assemble(tables: dict[str, bytes]) -> bytes:
    tags = sorted(tables)
    n = len(tags)
    search_range = 16 * (2 ** (n.bit_length() - 1))
    entry_selector = search_range.bit_length() - 1 - 4
    range_shift = n * 16 - search_range
    offset = 12 + n * 16
    directory = b""
    body = b""
    for tag in tags:
        data = tables[tag]
        directory += struct.pack(">4sIII", tag.encode("latin-1"), checksum(data), offset, len(data))
        padded = data + b"\0" * ((4 - len(data) % 4) % 4)
        body += padded
        offset += len(padded)
    header = struct.pack(">IHHHH", 0x00010000, n, search_range, entry_selector, range_shift)
    data = bytearray(header + directory + body)
    # head.checkSumAdjustment: 0xB1B0AFBA - (checksum of the whole file with the field zeroed)
    head_record = 12 + tags.index("head") * 16
    head_offset = struct.unpack(">I", bytes(data[head_record + 8:head_record + 12]))[0]
    struct.pack_into(">I", data, head_offset + 8, 0)
    adjustment = (0xB1B0AFBA - checksum(bytes(data))) & 0xFFFFFFFF
    struct.pack_into(">I", data, head_offset + 8, adjustment)
    return bytes(data)


def wanted_codepoints() -> set[int]:
    return set(range(0x20, 0x7F)) | {ord(c) for c in EXTRA_CHARS}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    wanted = wanted_codepoints()
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    for name, source in SOURCES.items():
        if not source.exists():
            raise SystemExit(f"source font missing: {source}")
        blob = subset(source, wanted)
        target = OUT_DIR / name
        if args.check:
            existing = target.read_bytes() if target.exists() else b""
            print(f"{name}: {'OK' if existing == blob else 'DRIFT'} "
                  f"({len(blob)} bytes, sha256 {hashlib.sha256(blob).hexdigest()[:16]})")
            continue
        target.write_bytes(blob)
        print(f"{name}: {len(blob)} bytes from {source.name} "
              f"({source.stat().st_size} bytes full) "
              f"sha256 {hashlib.sha256(blob).hexdigest()[:16]}")
    if not args.check:
        print(f"wrote into {OUT_DIR}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
